Entrypoints:
  - src/cli.cr
  # - spec/**/*_spec.cr

Documentation/DocumentationAdmonition:
  Timezone: UTC
  Admonitions: [FIXME, BUG]

Lint/Typos:
  Excluded:
    - spec/ameba/rule/lint/typos_spec.cr
