Documentation/DocumentationAdmonition:
  Timezone: UTC
  Admonitions: [FIXME, BUG]

Lint/Typos:
  Excluded:
    - spec/ameba/rule/lint/typos_spec.cr

Naming/KeywordNames:
  Enabled: true
  AllowedNames:
    - with
    - of
    - type
