name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: [latest, nightly]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set timezone to UTC
        uses: szenius/set-timezone@v2.0

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Download source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: shards install

      - name: Install typos-cli
        if: matrix.os == 'macos-latest'
        run: brew install typos-cli

      - name: Run specs
        run: make spec

      - name: Build ameba binary
        run: make build

      - name: Run ameba linter
        run: make lint

  github-ci-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ameba-version: ["nobody/github-ci-formatter"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Cache Ameba binary
        id: cache-ameba
        uses: actions/cache@v3
        with:
          path: bin/ameba
          key: ${{ runner.os }}-ameba-${{ matrix.ameba-version }}

      - name: Build Ameba
        if: steps.cache-ameba.outputs.cache-hit != 'true'
        run: |
          git clone --branch ${{ matrix.ameba-version }} --single-branch https://github.com/nobodywasishere/ameba.git
          cd ameba
          make
          mkdir -p ../bin
          mv bin/ameba ../bin/ameba
          cd ..
          rm -rf ameba

      - name: Run Ameba Linter
        run: bin/ameba -c .ameba.yml -f github_ci
